In [2]:
import numpy as np

# Performance difference

In [3]:
my_arr = np.arange(1000000)

In [4]:
my_list = list(range(1000000))

In [5]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 35.5 ms, sys: 23.7 ms, total: 59.2 ms
Wall time: 59.9 ms


In [6]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 497 ms, sys: 127 ms, total: 625 ms
Wall time: 624 ms


# A Multidimensional Array Object

In [7]:
data = np.random.randn(2,3)

In [9]:
data

array([[ 0.30770352, -0.36535686, -0.89348033],
       [ 1.42025255, -0.29178104,  0.63770535]])

In [10]:
data*10

array([[ 3.07703517, -3.65356861, -8.93480334],
       [14.20252555, -2.91781042,  6.37705349]])

In [11]:
data + data

array([[ 0.61540703, -0.73071372, -1.78696067],
       [ 2.84050511, -0.58356208,  1.2754107 ]])

In [12]:
data.shape

(2, 3)

In [13]:
data.dtype

dtype('float64')

# Creating ndarrays

In [14]:
data1 = [6,7,8.5,0,1]

In [15]:
arr1 = np.array(data1)

In [16]:
arr1

array([6. , 7. , 8.5, 0. , 1. ])

In [17]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [18]:
arr2 = np.array(data2)

In [19]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
arr2.ndim

2

In [21]:
arr2.shape

(2, 4)

In [22]:
arr1.shape

(5,)

In [24]:
arr1.dtype

dtype('float64')

In [25]:
arr2.dtype

dtype('int64')

In [26]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
np.empty((2,3,2))

array([[[4.67789134e-310, 0.00000000e+000],
        [1.01855798e-312, 9.54898106e-313],
        [1.14587773e-312, 1.03977794e-312]],

       [[1.23075756e-312, 1.08221785e-312],
        [1.08221785e-312, 9.76118064e-313],
        [1.20953760e-312, 1.90979621e-312]]])

In [30]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Array creation functions

# array

In [32]:
alist = [1,2,3,4,5]

In [33]:
np.array(alist)

array([1, 2, 3, 4, 5])

In [34]:
atuple = (1,2,3,4,5)

In [36]:
np.array(atuple)

In [37]:
a = np.array(atuple)

# asarray


In [40]:
np.asarray(a)

array([1, 2, 3, 4, 5])

# arange

In [41]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.arange(10,30)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [45]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

# ones

In [48]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [49]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [50]:
np.ones((2,3,4), dtype = "int")

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

# ones_like

In [52]:
a

array([1, 2, 3, 4, 5])

In [51]:
np.ones_like(a)

array([1, 1, 1, 1, 1])

# zeros

In [53]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [54]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [55]:
np.zeros((2,3,4), dtype = "int")

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

# zeros_like

In [57]:
a

array([1, 2, 3, 4, 5])

In [56]:
np.zeros_like(a)

array([0, 0, 0, 0, 0])

# full

In [62]:
np.full(shape = (2,4), fill_value = 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [65]:
np.full((2,3), 3)

array([[3, 3, 3],
       [3, 3, 3]])

# full_like

In [68]:
a

array([1, 2, 3, 4, 5])

In [67]:
np.full_like(a, 10)

array([10, 10, 10, 10, 10])

# eye

In [69]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [70]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# identity

In [71]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [72]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])