In [1]:
import numpy as np

# 1-D

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[5]

5

In [5]:
arr[5:8]

array([5, 6, 7])

In [6]:
arr[5:8] = 12

In [7]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [14]:
arr_slice = arr[5:8]

In [9]:
arr_slice

array([12, 12, 12])

In [15]:
arr_slice[1] = 12345

In [16]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [17]:
arr_slice[:] = 64

In [18]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

# 2-D

In [19]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [20]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr2d[2]

array([7, 8, 9])

In [22]:
arr2d[0][2]

3

In [23]:
arr2d[0,2]

3

# 3-D

In [24]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [25]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [28]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
old_values = arr3d[0].copy()

In [33]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr3d[0] = 42

In [32]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [34]:
arr3d[0] = old_values

In [35]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [36]:
arr3d[1,0]

array([7, 8, 9])

In [37]:
arr3d[1][0]

array([7, 8, 9])

In [38]:
x = arr3d[1]

In [39]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [40]:
x[0]

array([7, 8, 9])

# Indexing with slices

In [41]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [42]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [43]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [46]:
arr2d[1, :2]

array([4, 5])

In [47]:
arr2d[:2, 2]

array([3, 6])

In [48]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [49]:
arr2d[:2, 1:] = 0

In [50]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

# Boolean Indexing

In [51]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [52]:
data = np.random.randn(7, 4)

In [54]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [55]:
data

array([[ 1.33319239, -0.21771232,  0.19998501,  1.1240205 ],
       [ 0.71677898,  0.40690176, -0.00990178,  0.52536807],
       [-0.54559143, -0.51242951,  0.21830673, -1.25912405],
       [-2.78629154, -0.81611431,  1.99896102,  0.23669054],
       [ 1.98202985, -0.26962574, -0.4925884 , -1.14546141],
       [-0.96449661, -0.34238659,  0.16723513,  0.67935295],
       [-1.40904198, -2.19609991, -1.08505721, -0.88732909]])

In [56]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [58]:
data[names == "Bob"]

array([[ 1.33319239, -0.21771232,  0.19998501,  1.1240205 ],
       [-2.78629154, -0.81611431,  1.99896102,  0.23669054]])

In [59]:
data[names == "Bob", 2:]

array([[0.19998501, 1.1240205 ],
       [1.99896102, 0.23669054]])

In [60]:
data[names == "Bob", 3]

array([1.1240205 , 0.23669054])

In [61]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [63]:
data

array([[ 1.33319239, -0.21771232,  0.19998501,  1.1240205 ],
       [ 0.71677898,  0.40690176, -0.00990178,  0.52536807],
       [-0.54559143, -0.51242951,  0.21830673, -1.25912405],
       [-2.78629154, -0.81611431,  1.99896102,  0.23669054],
       [ 1.98202985, -0.26962574, -0.4925884 , -1.14546141],
       [-0.96449661, -0.34238659,  0.16723513,  0.67935295],
       [-1.40904198, -2.19609991, -1.08505721, -0.88732909]])

In [62]:
data[~(names == "Bob")]

array([[ 0.71677898,  0.40690176, -0.00990178,  0.52536807],
       [-0.54559143, -0.51242951,  0.21830673, -1.25912405],
       [ 1.98202985, -0.26962574, -0.4925884 , -1.14546141],
       [-0.96449661, -0.34238659,  0.16723513,  0.67935295],
       [-1.40904198, -2.19609991, -1.08505721, -0.88732909]])

In [64]:
mask = (names == "Bob") | (names == "Will")

In [66]:
mask

array([ True, False,  True,  True,  True, False, False])

In [65]:
data[mask]

array([[ 1.33319239, -0.21771232,  0.19998501,  1.1240205 ],
       [-0.54559143, -0.51242951,  0.21830673, -1.25912405],
       [-2.78629154, -0.81611431,  1.99896102,  0.23669054],
       [ 1.98202985, -0.26962574, -0.4925884 , -1.14546141]])

In [67]:
data[data<0] = 0

In [68]:
data

array([[1.33319239, 0.        , 0.19998501, 1.1240205 ],
       [0.71677898, 0.40690176, 0.        , 0.52536807],
       [0.        , 0.        , 0.21830673, 0.        ],
       [0.        , 0.        , 1.99896102, 0.23669054],
       [1.98202985, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.16723513, 0.67935295],
       [0.        , 0.        , 0.        , 0.        ]])

In [69]:
data[names != "Joe"] = 7

In [70]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.71677898, 0.40690176, 0.        , 0.52536807],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.16723513, 0.67935295],
       [0.        , 0.        , 0.        , 0.        ]])

# Fancy Indexing

In [71]:
arr = np.empty((8, 4))

In [72]:
for i in range(8):
    arr[i] = i

In [73]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [74]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [75]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [76]:
arr = np.arange(32).reshape((8, 4))

In [77]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [79]:
arr[[1,5,7,2], [0,3,1,2]]

array([ 4, 23, 29, 10])

In [80]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

# Transposing Arrays and Swapping Axes

In [81]:
arr = np.arange(15).reshape((3,5))

In [82]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [83]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [84]:
arr = np.random.randn(6, 3)

In [85]:
arr

array([[ 1.18631958,  1.47526143,  1.04172315],
       [-0.68333208,  0.29202971,  0.62303305],
       [-1.07908969,  0.22646684, -0.79666204],
       [ 1.4932364 , -0.64397649, -0.78575218],
       [ 0.13459461, -1.0122162 , -0.45609245],
       [ 0.06514029, -0.02714827, -1.69093487]])

In [86]:
np.dot(arr.T, arr)

array([[5.29084536, 0.20658379, 0.32489856],
       [0.20658379, 3.75298925, 2.55191666],
       [0.32489856, 2.55191666, 5.79271525]])

In [89]:
arr = np.arange(16).reshape((2,2,4))

In [90]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [93]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [96]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [95]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])