In [1]:
import numpy as np

In [3]:
arr = np.arange(10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [6]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [7]:
x = np.random.randn(8)
y = np.random.randn(8)

In [8]:
np.maximum(x, y)

array([0.08836062, 0.44999534, 2.420268  , 0.18758371, 1.64096069,
       1.14908496, 0.2282321 , 0.60040844])

In [9]:
arr = np.random.randn(7) * 5

In [10]:
arr

array([ 1.52497012,  0.91991382, -0.51833516,  0.63382624,  3.46427401,
        1.40224106, -0.32307586])

In [11]:
remainder, whole_part = np.modf(arr)

In [12]:
remainder

array([ 0.52497012,  0.91991382, -0.51833516,  0.63382624,  0.46427401,
        0.40224106, -0.32307586])

In [13]:
whole_part

array([ 1.,  0., -0.,  0.,  3.,  1., -0.])

In [14]:
arr

array([ 1.52497012,  0.91991382, -0.51833516,  0.63382624,  3.46427401,
        1.40224106, -0.32307586])

In [16]:
np.sqrt(arr)

/home/onstak/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([1.23489681, 0.95912138,        nan, 0.79613205, 1.86125603,
       1.1841626 ,        nan])

In [17]:
np.sqrt(arr, arr)

/home/onstak/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([1.23489681, 0.95912138,        nan, 0.79613205, 1.86125603,
       1.1841626 ,        nan])

In [18]:
arr

array([1.23489681, 0.95912138,        nan, 0.79613205, 1.86125603,
       1.1841626 ,        nan])